### ISSUE TITLE
[Chapter 7] nullpointer in GLGameTest ch07

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luisabellan/beginning-android-games#19]
```


i try to run your source code but this example(GLGameTest in chaptef 07) has 
error. someone explains to me!

java.lang.NullPointerException

at 
com.badlogic.androidgames.framework.impl.GLGame.onSurfaceCreated(GLGame.java:72)

at 
com.badlogic.androidgames.jumper.SuperJumper.onSurfaceCreated(SuperJumper.java:2
0)

at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1112)

at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:975)


```

Original issue reported on code.google.com by `c.ronald...@gmail.com` on 18 Jul 2011 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
did you type the example in by hand? Line 72 in GLGame.java in SVN can't 
produce a NullPointerException.
```

Original comment by `badlogicgames` on 27 Aug 2011 at 11:57
- Changed title: **[Chapter 7] nullpointer in GLGameTest ch07**
- Changed state: **Done**
